// Mico Work Match — job data (factory/manufacturing) — English
// Photo: hero image for each job (real photography)
window.WM_JOBS = [
  {
    id: "J-20451",
    title: "Auto Parts Assembly & Inspection",
    company: "Aoba Seiki Co., Ltd.",
    companySize: "820 employees",
    location: "Toyota City, Aichi",
    locationShort: "Toyota City",
    access: "15 min by bus from Meitetsu Mikawa Line 'Toyota-shi' Station",
    wage: 1680,
    wageType: "Hourly",
    wageNote: "Monthly example ¥336,000 + overtime",
    category: "Manufacturing",
    subcategory: "Assembly & Inspection",
    shift: "2-shift rotation / day shifts available",
    tags: ["Free dorm", "No experience needed", "Weekly pay OK", "Couple dorm"],
    photo: "assets/job-factory.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "FACTORY · ASSEMBLY",
    artIcon: "precision_manufacturing",
    match: 94,
    matchReason: "Close to your dorm and hourly-wage preferences",
    highlights: [
      "Sign-on bonus up to ¥300,000",
      "Cafeteria (¥300+ per meal)",
      "Private dorm with appliances & furniture",
    ],
    desc: "Assembly and inspection of auto parts at a factory supplying major Japanese automakers. Mostly line work with well-documented procedures, so beginners can start with confidence.",
    shiftDetails: ["Early: 6:30–15:15", "Late: 15:15–24:00"],
    welfare: ["Full social insurance", "Paid leave", "Commute allowance", "Work uniform provided", "Free dorm (up to 12 months)"],
  },
  {
    id: "J-20452",
    title: "Food Factory Packaging & Sorting",
    company: "Harumachi Foods",
    companySize: "350 employees",
    location: "Soka City, Saitama",
    locationShort: "Soka City",
    access: "8 min walk from Tobu Skytree Line 'Yatsuka' Station",
    wage: 1320,
    wageType: "Hourly",
    wageNote: "Monthly example ¥245,000",
    category: "Manufacturing",
    subcategory: "Food & Packaging",
    shift: "Day shift only",
    tags: ["Day shift only", "Climate controlled", "Women welcome", "Near station"],
    photo: "assets/job-retail.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "FOOD PACKING",
    artIcon: "restaurant",
    match: 88,
    matchReason: "Matches your day-shift × near-station preferences",
    highlights: [
      "Fixed weekends off",
      "Free uniform",
      "Same wage during training",
    ],
    desc: "Packaging, label application, and sorting of frozen prepared foods. Mostly seated work — physically light environment.",
    shiftDetails: ["Day: 8:30–17:30 (8h actual)"],
    welfare: ["Social insurance", "Paid leave", "Employee discount", "Uniform provided"],
  },
  {
    id: "J-20453",
    title: "Semiconductor Equipment Operator",
    company: "NK Electronics",
    companySize: "1,200 employees",
    location: "Yokkaichi City, Mie",
    locationShort: "Yokkaichi City",
    access: "Shuttle bus from JR Kansai Main Line 'Minami-Yokkaichi' Station",
    wage: 1850,
    wageType: "Hourly",
    wageNote: "Monthly example ¥382,000 + perfect-attendance bonus",
    category: "Manufacturing",
    subcategory: "Semiconductor",
    shift: "3-shift rotation",
    tags: ["High wage", "Free dorm", "Career path to permanent", "Shuttle bus"],
    photo: "assets/job-factory.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "SEMICONDUCTOR",
    artIcon: "memory",
    match: 91,
    matchReason: "High-wage role matching your ¥1,800+/h target",
    highlights: [
      "Perfect-attendance bonus ¥30,000/month",
      "Studio dorm with Wi-Fi",
      "Wage review every 6 months",
    ],
    desc: "Operate semiconductor manufacturing equipment — button operation, material refilling, and data entry. Cleanroom environment with full climate control for comfort.",
    shiftDetails: ["Early / Late / Night — 3-shift rotation"],
    welfare: ["Full social insurance", "Free dorm", "Shuttle bus", "Attendance bonus ¥30,000"],
  },
  {
    id: "J-20454",
    title: "Call Center Staff",
    company: "Medicorp Kurume",
    companySize: "460 employees",
    location: "Kurume City, Fukuoka",
    locationShort: "Kurume City",
    access: "5 min walk from JR Kyudai Main Line 'Kurume' Station",
    wage: 1450,
    wageType: "Hourly",
    wageNote: "Monthly example ¥278,000",
    category: "Office",
    subcategory: "Call Center",
    shift: "Day shift only",
    tags: ["Remote OK", "Climate controlled", "No experience needed", "Long-term welcome"],
    photo: "assets/job-call.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "CALL CENTER",
    artIcon: "headset_mic",
    match: 79,
    matchReason: "Matches your climate-controlled × weekends-off preferences",
    highlights: ["Full 2-day weekend", "Comprehensive training", "Near station"],
    desc: "Handle customer inquiries. Comprehensive manuals available — beginners can start with confidence.",
    shiftDetails: ["Day: 9:00–18:00 (8h actual)"],
    welfare: ["Social insurance", "Paid leave", "Uniform provided", "Full commute allowance"],
  },
  {
    id: "J-20455",
    title: "General Office & Data Entry",
    company: "Logiplus Kanto",
    companySize: "280 employees",
    location: "Ichikawa City, Chiba",
    locationShort: "Ichikawa City",
    access: "6 min walk from JR Sobu Line 'Ichikawa' Station",
    wage: 1280,
    wageType: "Hourly",
    wageNote: "Monthly example ¥238,000",
    category: "Office",
    subcategory: "General Admin",
    shift: "Day shift only",
    tags: ["Day shift", "Weekdays only", "Flexible hours", "Side-job OK"],
    photo: "assets/job-office.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "OFFICE · DATA ENTRY",
    artIcon: "desktop_windows",
    match: 72,
    matchReason: "Roughly matches your weekday-shift preference",
    highlights: ["From 4h/day OK", "No CV required", "Same-day start OK"],
    desc: "Order data entry, document organization, and phone reception — general office work overall.",
    shiftDetails: ["Day: 9:00–18:00 (1h break)"],
    welfare: ["Social insurance", "Commute allowance", "Side-jobs allowed"],
  },
  {
    id: "J-20456",
    title: "Apparel Sales Staff",
    company: "Nishioka Select",
    companySize: "540 employees",
    location: "Higashi-Osaka City, Osaka",
    locationShort: "Higashi-Osaka",
    access: "2 min walk from Kintetsu Nara Line 'Yaenosato' Station",
    wage: 1580,
    wageType: "Hourly",
    wageNote: "Monthly example ¥305,000 + commission",
    category: "Retail",
    subcategory: "Apparel",
    shift: "Shift work",
    tags: ["Employee discount", "Career path to permanent", "Near station"],
    photo: "assets/job-retail.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "RETAIL · APPAREL",
    artIcon: "storefront",
    match: 85,
    matchReason: "Matches your sales/customer-service background",
    highlights: ["30% employee discount", "Sales commission", "Free hairstyle policy"],
    desc: "Apparel sales for a casual brand. Customer service, restocking, and fitting-room support.",
    shiftDetails: ["Early: 10:00–19:00", "Late: 12:00–21:00"],
    welfare: ["Social insurance", "Employee discount", "Commute allowance"],
  },
];

window.WM_HISTORY_LIKED = [
  { jobId: "J-20451", date: "Apr 21", reason: "Wage" },
  { jobId: "J-20453", date: "Apr 20", reason: "Dorm/Housing" },
  { jobId: "J-20456", date: "Apr 18", reason: "Location" },
];

window.WM_HISTORY_SKIPPED = [
  { jobId: "J-20455", date: "Apr 21", reason: "Far" },
  { jobId: "J-20454", date: "Apr 20", reason: "Shift mismatch" },
];
